namespace: alpha

replicaCount: 1
image:
    repository: docker.neutrinos.co/plugins-server
    pullPolicy: Always
    tag: '1.0.0'

imagePullSecrets:
    - name: regcred

nameOverride: 'plugins-service'
fullnameOverride: 'plugins-service'
podAnnotations: {}
podLabels: {}

service:
    type: ClusterIP
    port: 4000
    targetPort: 4000

ingress:
    enabled: true
    className: nginx
    annotations: {}
    hosts:
        - host: alpha.neutrinos-apps.com
          paths:
              - path: /plugins-service
                pathType: Prefix
    tls: []

env:
    - name: PORT
      value: '3000'

resources:
    limits:
        cpu: '500m'
        memory: '512Mi'
    requests:
        cpu: '250m'
        memory: '256Mi'

livenessProbe:
    httpGet:
        path: /plugins-service/ping
        port: 3000
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
readinessProbe:
    httpGet:
        path: /plugins-service/ping
        port: 3000
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3

autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
