export const darkTokens = {
    id: 'dark',
    name: 'Obsidian Azure',
    tokens: {
        '--uiv-primary-color': '#3b82f6',
        '--uiv-secondary-color': '#94a3b8',
        '--uiv-accent-color': '#60a5fa',
        '--uiv-bg-color': '#0f172a',
        '--uiv-surface-color': '#1e293b',
        '--uiv-bg-surface': '#1e293b',
        '--uiv-text-color': '#f1f5f9',
        '--uiv-text-muted': '#cbd5e1',
        '--uiv-border-color': '#334155',
        '--uiv-glow-intensity': '0.3',
        '--uiv-border-glow': '0 0 20px rgba(59, 130, 246, 0.1)',
        '--uiv-shadow-depth': '0 10px 15px rgba(0,0,0,0.5)',
        '--uiv-glass-blur': '12px',
        
        // Extended Reference Tokens
        '--uiv-bg-primary': '#0f172a',
        '--uiv-bg-secondary': '#1e293b',
        '--uiv-bg-tertiary': '#334155',
        '--uiv-bg-inverse': '#ffffff',
        '--uiv-surface-primary': '#1e293b',
        '--uiv-surface-secondary': '#0f172a',
        '--uiv-surface-elevated': '#1e293b',
        '--uiv-text-primary': '#f1f5f9',
        '--uiv-text-secondary': '#cbd5f5',
        '--uiv-text-tertiary': '#94a3b8',
        '--uiv-text-inverse': '#0f172a',
        '--uiv-text-disabled': '#64748b',
        '--uiv-color-primary': '#3b82f6',
        '--uiv-color-primary-hover': '#2563eb',
        '--uiv-color-primary-active': '#1d4ed8',
        '--uiv-color-secondary': '#94a3b8',
        '--uiv-color-success': '#22c55e',
        '--uiv-color-warning': '#fbbf24',
        '--uiv-color-danger': '#ef4444',
        '--uiv-color-info': '#38bdf8',
        '--uiv-btn-bg': 'var(--uiv-color-primary)',
        '--uiv-btn-text': '#ffffff',
        '--uiv-input-bg': '#0f172a',
        '--uiv-input-border': '#475569',

        // App Tokens
        '--uiv-app-bg': '#0f172a',
        '--uiv-app-sidebar-bg': '#1e293b',
        '--uiv-app-header-bg': '#0f172a',
        '--uiv-app-card-bg': '#1e293b',
        '--uiv-app-input-bg': '#0f172a',
        '--uiv-app-accent-color': '#3b82f6',
        '--uiv-app-accent-transparent': 'rgba(59, 130, 246, 0.2)',
        '--uiv-app-text-color': '#f1f5f9',
        '--uiv-app-text-muted': '#94a3b8',
        '--uiv-app-border-color': '#334155',
        '--uiv-app-hover-shadow': '0 10px 15px rgba(0,0,0,0.6)',
    }
};
