export const lightTokens = {
    id: 'light',
    name: 'Clean Light',
    tokens: {
        '--uiv-primary-color': '#8b5cf6',
        '--uiv-secondary-color': '#64748b',
        '--uiv-accent-color': '#d946ef',
        '--uiv-bg-color': '#f8fafc',
        '--uiv-surface-color': '#ffffff',
        '--uiv-bg-surface': '#ffffff',
        '--uiv-text-color': '#1e293b',
        '--uiv-text-muted': '#64748b',
        '--uiv-border-color': '#e2e8f0',
        '--uiv-glow-intensity': '0.15',
        '--uiv-border-glow': '0 0 15px rgba(139, 92, 246, 0.1)',
        '--uiv-shadow-depth': '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -4px rgba(0, 0, 0, 0.1)',
        '--uiv-glass-blur': 'blur(12px)',
        
        // Extended Reference Tokens
        '--uiv-bg-primary': '#f8fafc',
        '--uiv-bg-secondary': '#f1f5f9',
        '--uiv-bg-tertiary': '#e2e8f0',
        '--uiv-bg-inverse': '#1e293b',
        '--uiv-surface-primary': '#ffffff',
        '--uiv-surface-secondary': '#f9fafb',
        '--uiv-surface-elevated': '#ffffff',
        '--uiv-text-primary': '#1e293b',
        '--uiv-text-secondary': '#64748b',
        '--uiv-text-tertiary': '#94a3b8',
        '--uiv-text-inverse': '#ffffff',
        '--uiv-text-disabled': '#cbd5e1',
        '--uiv-color-primary': '#8b5cf6',
        '--uiv-color-primary-hover': '#7c3aed',
        '--uiv-color-primary-active': '#6d28d9',
        '--uiv-color-secondary': '#475569',
        '--uiv-color-success': '#10b981',
        '--uiv-color-warning': '#f59e0b',
        '--uiv-color-danger': '#ef4444',
        '--uiv-color-info': '#0ea5e9',
        '--uiv-btn-bg': 'var(--uiv-color-primary)',
        '--uiv-btn-text': '#ffffff',
        '--uiv-input-bg': '#ffffff',
        '--uiv-input-border': '#e2e8f0',

        // App Tokens
        '--uiv-app-bg': '#f8fafc',
        '--uiv-app-sidebar-bg': '#f1f5f9',
        '--uiv-app-sidebar-text': '#1e293b',
        '--uiv-app-header-bg': 'rgba(255, 255, 255, 0.8)',
        '--uiv-app-card-bg': '#ffffff',
        '--uiv-app-input-bg': '#ffffff',
        '--uiv-app-accent-color': '#8b5cf6',
        '--uiv-app-accent-transparent': 'rgba(139, 92, 246, 0.08)',
        '--uiv-app-text-color': '#1e293b',
        '--uiv-app-text-muted': '#64748b',
        '--uiv-app-border-color': 'rgba(226, 232, 240, 0.8)',
        '--uiv-app-hover-shadow': '0 20px 25px -5px rgba(139, 92, 246, 0.1), 0 8px 10px -6px rgba(139, 92, 246, 0.1)',
        '--uiv-app-glass-blur': 'blur(12px)',
    }
};
