export const lightTokens = {
    id: 'light',
    name: 'Clean Light',
    tokens: {
        '--uiv-primary-color': '#2563eb',
        '--uiv-secondary-color': '#64748b',
        '--uiv-accent-color': '#2563eb',
        '--uiv-bg-color': '#ffffff',
        '--uiv-surface-color': '#ffffff',
        '--uiv-bg-surface': '#ffffff',
        '--uiv-text-color': '#1a1a1a',
        '--uiv-text-muted': '#4a5568',
        '--uiv-border-color': '#e2e8f0',
        '--uiv-glow-intensity': '0.1',
        '--uiv-border-glow': '0 0 10px rgba(37, 99, 235, 0.1)',
        '--uiv-shadow-depth': '0 4px 6px rgba(0,0,0,0.1)',
        '--uiv-glass-blur': '0px',
        
        // Extended Reference Tokens
        '--uiv-bg-primary': '#ffffff',
        '--uiv-bg-secondary': '#f5f6f8',
        '--uiv-bg-tertiary': '#e9ebef',
        '--uiv-bg-inverse': '#1a1a1a',
        '--uiv-surface-primary': '#ffffff',
        '--uiv-surface-secondary': '#f9fafb',
        '--uiv-surface-elevated': '#ffffff',
        '--uiv-text-primary': '#1a1a1a',
        '--uiv-text-secondary': '#4a5568',
        '--uiv-text-tertiary': '#718096',
        '--uiv-text-inverse': '#ffffff',
        '--uiv-text-disabled': '#a0aec0',
        '--uiv-color-primary': '#2563eb',
        '--uiv-color-primary-hover': '#1d4ed8',
        '--uiv-color-primary-active': '#1e40af',
        '--uiv-color-secondary': '#64748b',
        '--uiv-color-success': '#16a34a',
        '--uiv-color-warning': '#f59e0b',
        '--uiv-color-danger': '#dc2626',
        '--uiv-color-info': '#0ea5e9',
        '--uiv-btn-bg': 'var(--uiv-color-primary)',
        '--uiv-btn-text': '#ffffff',
        '--uiv-input-bg': '#ffffff',
        '--uiv-input-border': '#cbd5e1',

        // App Tokens
        '--uiv-app-bg': '#ffffff',
        '--uiv-app-sidebar-bg': '#ffffff',
        '--uiv-app-header-bg': '#ffffff',
        '--uiv-app-input-bg': '#ffffff',
        '--uiv-app-accent-color': '#2563eb',
        '--uiv-app-text-color': '#1a1a1a',
        '--uiv-app-text-muted': '#64748b',
        '--uiv-app-border-color': '#e2e8f0',
        '--uiv-app-hover-shadow': '0 10px 15px rgba(0,0,0,0.15)',
    }
};
