// Auto-generated by /marketplace/publish-node for "zero-flow-node-uppercase".
export async function execute(config, input, context) {
const text = String((input && input.text) ?? config.text ?? "");
return { output: { ...input, text: text.toUpperCase(), uppercased: true } };
}
