export const corporateTokens = {
    id: 'corporate',
    name: 'Corporate Pro',
    tokens: {
        '--uiv-primary-color': '#0047ab',
        '--uiv-secondary-color': '#6b7280',
        '--uiv-accent-color': '#0047ab',
        '--uiv-bg-color': '#f4f6f9',
        '--uiv-surface-color': '#ffffff',
        '--uiv-bg-surface': '#ffffff',
        '--uiv-text-color': '#1f2937',
        '--uiv-text-muted': '#4b5563',
        '--uiv-border-color': '#d1d5db',
        '--uiv-glow-intensity': '0.3',
        '--uiv-border-glow': '0 0 15px rgba(0, 71, 171, 0.2)',
        '--uiv-shadow-depth': '0 8px 16px rgba(0,0,0,0.1)',
        '--uiv-glass-blur': '0px',
        
        // Extended Reference Tokens
        '--uiv-bg-primary': '#f4f6f9',
        '--uiv-bg-secondary': '#e6ebf1',
        '--uiv-bg-tertiary': '#d1d9e6',
        '--uiv-bg-inverse': '#1a1a1a',
        '--uiv-surface-primary': '#ffffff',
        '--uiv-surface-secondary': '#f9fafb',
        '--uiv-surface-elevated': '#ffffff',
        '--uiv-text-primary': '#1a1a1a',
        '--uiv-text-secondary': '#4a5568',
        '--uiv-text-tertiary': '#718096',
        '--uiv-text-inverse': '#ffffff',
        '--uiv-text-disabled': '#a0aec0',
        '--uiv-color-primary': '#0047ab',
        '--uiv-color-primary-hover': '#003a8c',
        '--uiv-color-primary-active': '#002f6c',
        '--uiv-color-secondary': '#64748b',
        '--uiv-color-success': '#2e7d32',
        '--uiv-color-warning': '#ed6c02',
        '--uiv-color-danger': '#d32f2f',
        '--uiv-color-info': '#0288d1',
        '--uiv-btn-bg': 'var(--uiv-color-primary)',
        '--uiv-btn-text': '#ffffff',
        '--uiv-input-bg': '#ffffff',
        '--uiv-input-border': '#9ca3af',

        // App Tokens
        '--uiv-app-bg': '#f4f6f9',
        '--uiv-app-sidebar-bg': '#1f2937',
        '--uiv-app-sidebar-text': '#ffffff',
        '--uiv-app-header-bg': '#ffffff',
        '--uiv-app-card-bg': '#ffffff',
        '--uiv-app-input-bg': '#ffffff',
        '--uiv-app-accent-color': '#0047ab',
        '--uiv-app-accent-transparent': 'rgba(0, 71, 171, 0.15)',
        '--uiv-app-text-color': '#1a1a1a',
        '--uiv-app-text-muted': '#4a5568',
        '--uiv-app-border-color': '#d1d5db',
        '--uiv-app-hover-shadow': '0 20px 40px -10px rgba(0, 71, 171, 0.25)',
        '--uiv-app-glass-blur': 'blur(0px)',
    }
};
